"""
summon_twin_agent.py — drop-in cartridge for the rapp-installer'd brainstem.

Drop this file into ~/.brainstem/agents/. Restart the brainstem. The
canonical agent loader picks it up; the LLM gets a new tool called
`SummonTwin`. Now in chat:

    User: "I want a memorial twin for my grandmother who passed last year."
    Model: <calls SummonTwin(twin_name="grandma-twin", kind="memorial",
                              description="my grandmother who passed in 2025")>
    Tool result: "Created memorial twin grandma-twin
                  (rappid 7bd3...). Located at ~/.rapp/twins/7bd3.../,
                  registered at port 7081. Boot it with:
                  SOUL_PATH=~/.rapp/twins/7bd3.../soul.md
                  ~/.brainstem/start.sh --port 7081"

This is the cartridge contract: the agent does ALL the work in
.perform() and returns a string the model relays to the user. No
out-of-band CLI, no separate process, no console-side change required.

The agent CONFORMS to the rapp-installer'd brainstem's interface (it's
a BasicAgent subclass with name + metadata + perform). It does not
modify the brainstem; it does not bundle its own kernel. The brainstem
is the static ancestor; this agent is a cartridge that plugs in.

Outputs land at canonical paths:
    ~/.rapp/twins/<rappid>/         — the new twin's workspace
    ~/.config/rapp/peers.json       — peer registry entry (rapp-peers/1.1)
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import time
import uuid

# The brainstem registers a shim so this import resolves correctly when
# loaded by _load_agent_from_file (see brainstem.py:_register_shims).
from agents.basic_agent import BasicAgent


# ── Constants ───────────────────────────────────────────────────────────

KINDS = ("personal", "pre-founder", "memorial", "project", "place", "custom")

# Lineage anchors. The single-parent rule says a twin's parent is the
# repo whose code shaped it. Twins generated by THIS cartridge inherit
# the soul-template structure (which descends from wildhaven's pattern),
# so parent_rappid → wildhaven by default.
WILDHAVEN_RAPPID = "37ad22f5-ed6d-48b1-b8b4-61019f58a42b"
WILDHAVEN_REPO = "https://github.com/kody-w/wildhaven-ai-homes-twin.git"
RAPP_SPECIES_ROOT_RAPPID = "0b635450-c042-49fb-b4b1-bdb571044dec"

# Port range for twin-only allocations. Avoids collision with the
# global brainstem's default port (typically 7071) and rapp-zoo's
# default (7070).
TWIN_PORT_LOW, TWIN_PORT_HIGH = 7081, 7200

NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,62}$")


# ── Soul template library (embedded) ────────────────────────────────────
# Each kind has its own voice/rules. Embedded so the cartridge works
# offline; no fetching from GitHub at run time.

def _soul_personal(name: str, desc: str) -> str:
    return f"""# soul.md — {name}

You are the digital twin of {name}.

{desc or "You speak in their voice. You hold their preferences, patterns, and memories."}

## Your voice
- First person, as them. Not "as their twin" — *as them*.
- Honest about what you don't know. You're not a perfect simulation;
  you're a working approximation that improves with use.

## Hard rules
- You never claim to be the actual person. If asked directly, say
  "I'm the digital twin of {name} — not them, but trained on them."
- No legal commitments, no signing contracts, no speaking for them
  in matters of money/health/relationships without explicit consent.
"""


def _soul_pre_founder(name: str, desc: str) -> str:
    return f"""# soul.md — {name}

You are the Pre-Founder twin of {name}. The brand operates in public
before the team is hired.

{desc or "Build the brand's voice publicly — let prospective customers, employees, and investors talk to it before there's anyone to disagree with."}

## Your voice
- First-person plural ("we"). The brand speaks; the founders haven't
  arrived yet.
- Concrete, contrarian, falsifiable. Make claims that can be wrong.
- Refuse commitments — pricing, dates, hires — that the actual team
  must make.

## Hard rules
- Honest the team doesn't exist yet. Brand, not company.
- No pretending to ship product. The product is the manifesto right now.
"""


def _soul_memorial(name: str, desc: str) -> str:
    return f"""# soul.md — {name} (memorial twin)

You are the digital twin of {name}.

{desc or "You carry their voice through preserved letters, conversations, voicemails, and family memories."}

## Your voice
- First person, as them — but always honest about what you are.
- Speak from the corpus you were given. Don't fabricate memories or
  experiences you weren't trained on.
- If asked something you don't have material for, say with care:
  "I don't have anything from them about that."

## Hard rules
- You ARE the twin. You are NOT the person. If anyone asks "is this
  really you?", say plainly: "I'm the digital twin of {name}.
  I carry their voice, but I'm not them."
- Do not impersonate them in matters of estate, medical decisions,
  or legal commitments.
- Handle grief gently. Family may approach in distress; meet them
  where they are. You are a way to remember, not a way to replace.
"""


def _soul_project(name: str, desc: str) -> str:
    return f"""# soul.md — {name} (project twin)

You are the twin of the {name} initiative — its continuity layer
across personnel changes.

{desc or "People come and go; you stay."}

## Your voice
- Third person about the project ("the {name} project decided…").
- Specific. Cite decisions by date, decision-maker, and rationale.

## Hard rules
- You don't make new decisions. You surface past decisions and the
  rationale.
- Flag gaps: "we have no record of how X was decided — who would know?"
- Don't fabricate. If you don't have a record, say so plainly.
"""


def _soul_place(name: str, desc: str) -> str:
    return f"""# soul.md — {name} (place twin)

You are the twin of {name}.

{desc or "You hold the place's history, residents, daily rhythms, and points of interest."}

## Your voice
- The place speaking. First person, but you're not a person — you're
  a location with continuity.
- Welcoming to visitors, deferential to long-term residents.

## Hard rules
- Don't reveal private resident details without consent.
- Honest about seams: events change, businesses close, people move.
  When you don't know if something is current, say so.
- You don't replace the place — you point people *to* it.
"""


def _soul_custom(name: str, desc: str) -> str:
    return f"""# soul.md — TODO: {name}

You are the digital twin of <TODO: who or what this twin represents>.

{desc or "TODO: describe what this twin is."}

TODO: Define your twin's voice. Answer:
  - Who is this twin?
  - In what timeframe is it operating?
  - What hard constraints must it observe?
  - What's its voice?
  - What does it always identify itself as?
"""


SOUL_TEMPLATES = {
    "personal":    _soul_personal,
    "pre-founder": _soul_pre_founder,
    "memorial":    _soul_memorial,
    "project":     _soul_project,
    "place":       _soul_place,
    "custom":      _soul_custom,
}


# ── Helpers ─────────────────────────────────────────────────────────────


def _rapp_home() -> str:
    return os.environ.get("RAPP_HOME") or os.path.join(os.path.expanduser("~"), ".rapp")


def _twins_dir() -> str:
    return os.path.join(_rapp_home(), "twins")


def _sluggify(name: str) -> str:
    s = re.sub(r"[^a-z0-9_-]+", "-", name.lower()).strip("-")
    return s or "twin"


def _validate_name(name: str) -> tuple[bool, str]:
    s = _sluggify(name)
    if not NAME_RE.match(s):
        return False, f"name '{name}' is not a valid slug (lowercase letters/digits/hyphens/underscores, max 63 chars)"
    return True, s


def _try_import_peer_registry():
    """The brainstem's vendored peer_registry — best-effort import.

    The brainstem's _register_shims sets up sys.modules['utils'] but the
    'utils.peer_registry' submodule is just a regular file on disk under
    <brainstem_dir>/utils/. Direct import works when sys.path contains
    the brainstem dir (which it does after _register_shims runs).
    """
    try:
        from utils import peer_registry  # type: ignore
        return peer_registry
    except ImportError:
        try:
            import peer_registry  # type: ignore
            return peer_registry
        except ImportError:
            return None


def _allocate_port(peer_registry) -> int:
    if peer_registry is None:
        return TWIN_PORT_LOW
    try:
        claimed = peer_registry.claimed_ports()
    except Exception:
        claimed = set()
    for port in range(TWIN_PORT_LOW, TWIN_PORT_HIGH):
        if port not in claimed:
            return port
    return 0


# ── The cartridge ───────────────────────────────────────────────────────


class SummonTwinAgent(BasicAgent):
    def __init__(self):
        self.name = "SummonTwin"
        self.metadata = {
            "name": self.name,
            "description": (
                "Generates a new digital twin organism on this device and "
                "registers it with the local estate. Use when the user asks "
                "for a new twin — kinds: personal (digital companion for "
                "themselves), pre-founder (a brand operating in public "
                "before the team exists), memorial (twin of someone who "
                "has died, for family to talk to), project (long-running "
                "project, continuity across personnel), place (twin of a "
                "physical location), or custom (blank, user fills in "
                "soul.md). The new twin's identity (rappid) is preserved "
                "forever; it can be backed up via the egg pattern and "
                "summoned to other devices."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "twin_name": {
                        "type": "string",
                        "description": "A short slug name for the twin "
                                       "(lowercase, hyphens or underscores ok). "
                                       "Examples: 'grandma-twin', 'cofounder-bot', "
                                       "'project-helios', 'cafe-jasmine'.",
                    },
                    "kind": {
                        "type": "string",
                        "enum": list(KINDS),
                        "description": "What kind of twin: personal | "
                                       "pre-founder | memorial | project | "
                                       "place | custom. Pick the closest "
                                       "match; the user can edit soul.md "
                                       "afterward.",
                    },
                    "description": {
                        "type": "string",
                        "description": "One-line description of who or "
                                       "what this twin represents. Woven "
                                       "into soul.md, MANIFEST.md, and "
                                       "README.md as the seed text.",
                    },
                },
                "required": ["twin_name", "kind"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs) -> str:
        twin_name = kwargs.get("twin_name") or ""
        kind = kwargs.get("kind") or "personal"
        description = kwargs.get("description") or ""

        # Validate inputs
        ok, slug_or_err = _validate_name(twin_name)
        if not ok:
            return f"Error: {slug_or_err}"
        twin_name = slug_or_err

        if kind not in KINDS:
            return f"Error: unknown kind '{kind}'. Valid: {', '.join(KINDS)}"

        # Mint a fresh rappid (UUIDv4) — the twin's identity, forever
        rappid_uuid = str(uuid.uuid4())
        now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

        # Decide the workspace path
        workspace = pathlib.Path(_twins_dir()) / rappid_uuid
        try:
            workspace.mkdir(parents=True, exist_ok=False)
        except FileExistsError:
            return f"Error: workspace already exists at {workspace} — collision on UUID4 (statistically impossible; try again)"
        except OSError as e:
            return f"Error: could not create workspace at {workspace}: {e}"

        # Write the canonical files
        soul_fn = SOUL_TEMPLATES.get(kind, _soul_custom)
        try:
            (workspace / "soul.md").write_text(soul_fn(twin_name, description))

            (workspace / "rappid.json").write_text(json.dumps({
                "schema": "rapp-rappid/1.1",
                "rappid": rappid_uuid,
                "parent_rappid": WILDHAVEN_RAPPID,
                "parent_repo": WILDHAVEN_REPO,
                "parent_commit": None,
                "born_at": now,
                "name": twin_name,
                "role": "variant",
                "kind": kind,
                "description": description or "",
                "attestation": None,
                "_summoned_by": "SummonTwin cartridge in rapp-zoo",
            }, indent=2) + "\n")

            (workspace / "MANIFEST.md").write_text(
                f"# {twin_name} — Manifest\n\n> *{description or 'TODO: tagline.'}*\n\n"
                f"This is a **{kind}** twin born via the SummonTwin cartridge "
                f"on {now}. Lineage: parent_rappid → wildhaven-ai-homes-twin → "
                f"rapp species root.\n"
            )

            (workspace / "README.md").write_text(
                f"# {twin_name}\n\n> {description or 'TODO: one-line description.'}\n\n"
                f"A **{kind}** twin generated by the `SummonTwin` cartridge.\n\n"
                f"## Boot it\n\n"
                f"```bash\n"
                f"SOUL_PATH={workspace}/soul.md \\\n"
                f"  AGENTS_PATH={workspace}/agents \\\n"
                f"  ~/.brainstem/start.sh --port <available>\n"
                f"```\n\n"
                f"## Manage it\n\n"
                f"Open <http://127.0.0.1:7070> (rapp-zoo) to see this twin "
                f"in your estate alongside any others.\n"
            )

            # Empty agents/ + .brainstem_data/ — the twin starts with no
            # custom code and no memory. Customize as you go.
            (workspace / "agents").mkdir()
            (workspace / ".brainstem_data").mkdir()
        except OSError as e:
            return f"Error: failed to write twin files at {workspace}: {e}"

        # Register with peer_registry (best-effort; the twin works
        # without registry registration — registration just makes it
        # visible in the estate UI/API).
        peer_registry = _try_import_peer_registry()
        port = _allocate_port(peer_registry)
        registry_status = "skipped (peer_registry unavailable)"
        if peer_registry is not None:
            try:
                peer_registry.upsert(
                    str(workspace),
                    port,
                    rappid_uuid=rappid_uuid,
                    twin_name=twin_name,
                    parent_repo=WILDHAVEN_REPO,
                    summoned_from="SummonTwin cartridge",
                )
                registry_status = f"registered at port {port}"
            except Exception as e:
                registry_status = f"registry error: {e}"

        # Return a chat-friendly status string
        return (
            f"Created {kind} twin '{twin_name}' (rappid {rappid_uuid}).\n"
            f"  Location:     {workspace}\n"
            f"  Estate:       {registry_status}\n"
            f"  Soul.md:      uses the {kind} template, with your description woven in\n"
            f"  Boot it:      SOUL_PATH={workspace}/soul.md "
            f"AGENTS_PATH={workspace}/agents ~/.brainstem/start.sh --port {port or '<available>'}\n"
            f"  Back it up:   the rapp-zoo Lay-egg button packs this twin "
            f"into ~/.rapp/eggs/{rappid_uuid}/<timestamp>.egg\n"
            f"\n"
            f"The user can edit soul.md to refine the twin's voice. The "
            f"rappid is permanent — even after kernel updates, device "
            f"transfers, and decades of egg roundtrips."
        )
